### ISSUE TITLE
Possible to get all GPU temps from RTX 3080ti ?

### ISSUE THREAD

**Issue by hsterk** [kallex/PromDapter#12]
When I use the catch all, '(?<MetricName>.*)'   I still don't get half the GPU metrics including the Memory and Hotspot Temperatures.  Do I need to do something else?

**Comment by kallex** [comment]
I haven't used that kind of catchall (can't test right now), but that might be the issue - as there MetricName is empty in that case - and thus cannot be separated from other alike metrics because there is no name at all.

Can you test with following (that includes the MetricName):

'(?<MetricName>.*)'

**Comment by hsterk** [comment]
Yes, I have it exactly. With the catch all, only the  the extra temperatures and detail about CPU voltage and power are missing.

![TotalGPU](https://user-images.githubusercontent.com/1772580/129144224-a8a406b7-5769-40da-95e7-263780e7cf86.JPG)

**Comment by kallex** [comment]
I'll check if Martin (HWiNFO) knows about these - in shared memory interface or something.

**Comment by kallex** [comment]
Shouldn't be anything different from HWiNFO's side, so it likely is in my implementation somehow. I check if I can repro this with my RTX 3080, if the new metrics are available for that model as well.

**Comment by hsterk** [comment]
Thanks for looking into this so quickly.

I tried 
 ` - '(?<Entity_GPU>)(?<MetricName>.*)' `
and now everything shows up.

**Comment by kallex** [comment]
Thanks for clarifying it! 

It was boggling my mind, I was thinking if the positioning would make it "not appear" after the initial change. There could of course be "accidental match" o f some other metric that then hides the one you're trying to match. If the patterns match both the same, but the one before "throws away" extra details of the sensor name.
