### ISSUE TITLE
REQ: UPS data points

### ISSUE THREAD

**Issue by ianneub** [kallex/PromDapter#13]
I have a UPS plugged into my PC via USB. HWiNFO shows the data, but doesn't seem to be scrapped by PromDapter.

I'd love it if that data could end up in the `/metrics` listing.

Please let me know if you need help with testing or more info.

![Home](https://user-images.githubusercontent.com/17455/132265638-651fe1ff-686a-4d6b-8fb2-9fae20011d06.png)

**Comment by Qlink84** [comment]
take a look here:

https://www.hwinfo.com/forum/threads/prometheus-adapter-for-hwinfo-grafana-dashboard.6281/post-30862

**Comment by ianneub** [comment]
Thanks @Qlink84 - for some reason I'm not able to get any extra data in the `/metrics` output. I added the following lines to the `C:\Program Files\PromDapter\Prometheusmapping.yaml` file under the `mapping[0].patterns` (IndividualValues) key: 
```
    # UPS
    - '(?<Entity_UPS>)(?<MetricName>UPS Load|Input Voltage|Output Voltage|Charge Level|Estimated Runtime|AC Power|Charging|Discharging)'
    # Catch all
    - '(?<MetricName>.*)'
```
Then I restarted the `Prometheus Adapter` service. I do not see the `hwi_ups_*` metrics in the output.

**Comment by kallex** [comment]
I'm sorry, this is my fault. There are two files that are named deceivingly the same. The one you edited is "the reference" file that's not actually used. The right one, that is actually used, is:

C:\ProgramData\PromDapter\Prometheusmapping.yaml

**Comment by ianneub** [comment]
Works great. Thanks @kallex !
