### ISSUE TITLE
Distribute HWiNFO provider sources

### ISSUE THREAD

**Issue by tlusk** [kallex/PromDapter#15]
With the [license changes](https://www.hwinfo.com/forum/threads/important-changes-to-hwinfo64-coming-soon.7092/) of HWiNFO 7.x and the shared memory interface now being public, could you distribute the HWiNFO provider source code allowing PromDapter to be fully built from source code?

I briefly looked at modifying the [public C# SHM interface](https://www.hwinfo.com/forum/threads/shared-memory-interface-v2.1032/) to implement your IPromDapterService interface declarations, but it would be ideal to just open source the remaining hidden bits of this project.

**Comment by kallex** [comment]
@tlusk I just reactivated on this project and was going through the issues. Did you succeed on the part or can I help you further?

**Comment by tlusk** [comment]
It's been a while so I don't remember all the details but I believe I was able to get it building with what you provided above.  I'll close this ticket out.
