### ISSUE TITLE
some errors related to telegraf parsing

### ISSUE THREAD

**Issue by henriknoerr** [kallex/PromDapter#16]
Hey,

Awesome PromAdapter, thank you.

I do get some errors related to parsing the metrics when using telegraf. Not sure where the error is
I get the following error on a couple of metrics

2022-01-15T19:26:33Z E! [inputs.prometheus] Error in plugin: error reading metrics for http://x.x.x.x:10445/metrics: reading text format failed: text format parsing error in line 70: invalid metric name in comment 

The metrics are;
# HELP hwi_gpu_temperature_ïc GPU Temperature ï¿½C - GPU [#0]: NVIDIA GeForce RTX 2070 Super: 
# HELP hwi_drive_temperature_2_ïc Drive Temperature 2 ï¿½C - S.M.A.R.T.: Samsung SSD 980 PRO 1TB (S5GXNF0R892894E)

With the default yaml I can disable monitoring of the two above on my system, and it works.
If I want to get all metrics with;
    # Catch all
    - '(?<MetricName>.*)'

I get several more, which I am disabling right now - not sure if it is related to the value ' ï¿½C'

**Comment by henriknoerr** [comment]
it works if I disable any temperature related metric in hwinfo;
![image](https://user-images.githubusercontent.com/3092180/149636491-762c900e-16d9-4153-a2a3-d1d9651ebd3e.png)

**Comment by kallex** [comment]
Oh I have to check it if there's some unicode change. Is it only on that certain metric? 

You can try to rename it in HWiNFO as well as a workaround and see if the unicode vanishes with that.

**Comment by kallex** [comment]
I'll investigate this and its behavior on my Prometheus too. It indeed relates to HWiNFO starting to support unicode in beta channel now. I don't think renaming sensors is the way to go in the longer run.

Let me install the beta too and get more educated guess about the issue... and if PromDapter can provide a way to strip/convert unicode away if desired.

**Comment by kallex** [comment]
Simply updating to latest beta (7.17-4660) doesn't seem trigger the problem for me. The language is defaulted in English. What language are you using?

**Comment by henriknoerr** [comment]
English

**Comment by henriknoerr** [comment]
Since the error is on temperature only, I think it is the symbol for degrees? °C

**Comment by kallex** [comment]
Yeah it's the symbol. Does the problem appear in all of the temperatures or just few metriocs?

**Comment by henriknoerr** [comment]
all temperature metrics

**Comment by henriknoerr** [comment]
renaming solves nothing, since that is just the key being renamed - the error is in the value

**Comment by kallex** [comment]
Did you use PromDapter before with earlier versions of HWiNFO where it worked? Or has this been the case for you always.

The weird thing is, that in your example the Celsius symbol is also on metric name. For me it's only on the sensor name.

See, this is without the symbol:  hwi_drive_temperature_2_c

# HELP hwi_drive_temperature_2_c Drive Temperature 2 °C - S.M.A.R.T.: Samsung SSD 960 EVO 500GB (S3EUNX0JA20472A)
hwi_drive_temperature_2_c{unit="°C",sensor_type="SENSOR_TYPE_TEMP",sensor="Drive Temperature 2",source="S.M.A.R.T.: Samsung SSD 960 EVO 500GB (S3EUNX0JA20472A)",host="THEBALL4"} 72

**Comment by henriknoerr** [comment]
I just discovered the PromDapter yesterday - Guess I could revert back to stable and test

**Comment by kallex** [comment]
What browser did you use for rendering the visible page of /metrics? I wonder if it's still there, but my Chrome just doesn't show it. Btw do you use Discord or alike, I can put up a channel for this :-).

**Comment by henriknoerr** [comment]
sure let us take it there - and using Chrome

**Comment by kallex** [comment]
Here's the Discord link for the (at least for now) PromDapter Discord:
https://discord.gg/4dFpNGvX

**Comment by kallex** [comment]
So we got it figured out together :-). Something in beta (+ some systems) made C symbol render as undefined UTF-8 char.

Can you still check what version of beta you happened to have before testing/seeing it work on stable?

**Comment by henriknoerr** [comment]
just to close it here - it works in stable. Fix for now is renaming the temperature sensors manually.
Fix should probably be implemented in hwinfo - or some hack is needed in PromDapter.

**Comment by kallex** [comment]
Confirmed - the issue noticed in HWiNFO and was fixed in newest beta already also.
