### ISSUE TITLE
help text is not a valid utf8 string

### ISSUE THREAD

**Issue by zhuziyuan** [kallex/PromDapter#24]
hi， Unable to connect to prometheus, prompt is ”help text is not a valid utf8 string“

**Comment by kallex** [comment]
That is usually caused by some non-utf-8 character in the sensor name. Can you provide the output of following:

**NOTE!** If there is anything sensitive in the actual metrics, just provide the lower /help version.

http://localhost:10445/metrics 
and
http://localhost:10445/metrics/help

**Comment by zhuziyuan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zhuziyuan** [comment]
Thanks,  According to your method, the problem has been resolved..

**Comment by kallex** [comment]
If there is something generic that the PromDapter could also automatically do to the sensor names, I'm happy to apply it at that level as well.

If the solution now requires you to rename sensors it might become cumbersome. Unless its like one specific device causing this or something.
