### ISSUE TITLE
How add a CPU2 in json?

### ISSUE THREAD

**Issue by guilhermelirio** [kallex/PromDapter#5]
Hello! First of all, thank you for the system!
I was wondering how to add my water cooler to show on the json link (http: // localhost: 10445 / metrics / json).
In HWInfo, it appears as CPU2:

![Sem Título-4](https://user-images.githubusercontent.com/23419633/91627838-c3eef000-e990-11ea-8d79-d38e54d70ef1.png)

Sorry for my English.

**Comment by kallex** [comment]
Sorry for the delay; it should appear if you just match it in regexp, alike matching just CPU2 

`- '(?<Entity_Cooler>)(?<MetricName>CPU2)'`

or more flexibly to match any number

`- '(?<Entity_Cooler>)(?<MetricName>CPU\d+)'`

It will appear as "hwi_cooler_cpu2_rpm".

**Comment by guilhermelirio** [comment]
Hi @kallex , i'm copy and past in Prometheusmapping.yaml, and not appeared CPU2:

My JSON:
https://gist.github.com/guilhermelirio/2fc6d2f0ce5e08489c3b2728091916ff

My Prometheusmapping.yaml:

https://gist.github.com/guilhermelirio/cdd847db6f9411725d1bcc3889e5ab75

**Comment by kallex** [comment]
Looks right. Just to confirm, is this file at C:\ProgramData\PromDapter - folder (and not under "Program Files")? You can try to use url http://localhost:10445/metrics/reset just to confirm for resetting the internal cache.

**Comment by guilhermelirio** [comment]
> 
> 
> Looks right. Just to confirm, is this file at C:\ProgramData\PromDapter - folder (and not under "Program Files")? You can try to use url http://localhost:10445/metrics/reset just to confirm for resetting the internal cache.

Works!! Thanks!! =)
