### ISSUE TITLE
CORS support

### ISSUE THREAD

**Issue by adyanth** [kallex/PromDapter#6]
Right now, the API call does not allow CORS, so the JSON cannot be directly used in a browser. Please add the Access-Control-Allow-Origin=* header to the responses.

**Comment by kallex** [comment]
I added the normal "allow all" options, but didn't have time to test it. Can you try with just released version 0.9.17 and see if it would just hopefully work?

If it doesn't, I apologize and I will then proceed to test it and fix it properly.

**Comment by adyanth** [comment]
Yes! 0.9.17 seems to work just fine, thanks!
