### ISSUE TITLE
Telegraf inputs.prometheus support

### ISSUE THREAD

**Issue by JavaMachine** [kallex/PromDapter#7]
I am trying to scrape PromDapter output using InfluxDB's Telegraf client, which is [supported](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/prometheus/README.md) in Telegraf.

Here is my telegraf config:

```
[[inputs.prometheus]]
  urls = ["http://my_ip:10445/metrics"]
    metric_version = 2
    # metric_version = 1 tried this aswell
```

After restarting Telegraf, I see following error:

```
[inputs.prometheus] Error in plugin: error reading metrics for http://my_ip:10445/metrics: reading text format failed: text format parsing error in line 5: second HELP line for metric name "hwi_chipset_chipset"
```

I found out that Telegraf client does not allow duplicate metrics ([here](https://github.com/influxdata/telegraf/issues/8098), and [here](https://github.com/influxdata/telegraf/issues/8098)).

Here is what my /metrics looks like:

[metrics.txt](https://github.com/kallex/PromDapter/files/5958000/metrics.txt)

And here is my yaml config file:

[Prometheusmapping (2).txt](https://github.com/kallex/PromDapter/files/5958005/Prometheusmapping.2.txt)

I suspect, repos initial yaml config does not have duplicates, it seems I added them myself after discussion [here](https://github.com/kallex/PromDapter/issues/2)

**Comment by kallex** [comment]
I made an attempt to fix this, but my own system doesn't replicate the original issue. So if you could test it and report back if it's (any) better now.

The # HELP tag should merge up with "(multiple sensors)" mention when there are multiple sensors with same metric.

**Comment by JavaMachine** [comment]
[metrics2.txt](https://github.com/kallex/PromDapter/files/5974505/metrics2.txt)

This is how metrics now look like.

But on Telegram I am getting another error:

`[inputs.prometheus] Error in plugin: error reading metrics for http://my_ip:10445/metrics: reading text format failed: text format parsing error in line 287: unexpected end of input stream`

**Comment by kallex** [comment]
Apparently the line 287 is the last line so the stream really ends there. Might be the plugin is expecting linefeed even after the last line.

I'll make another build and let's see how it goes.

**Comment by kallex** [comment]
Can you test with the patched version and report back:
https://github.com/kallex/PromDapter/releases/tag/v0.9.19-beta

**Comment by JavaMachine** [comment]
![image](https://user-images.githubusercontent.com/5568121/107847421-3b182380-6e0d-11eb-882c-a8ab6e1a2af6.png)
I guess it is now working properly, now I have to adjust my grafana and move to influx db

**Comment by kallex** [comment]
I'll close this issue, as it seems to be resolved. Open a new one if you bump into any more issues :-).
