### ISSUE TITLE
Invalid Digital Signature on the .cab file

### ISSUE THREAD

**Issue by Dazog** [kallex/PromDapter#9]
Cannot install this on my windows 10 machine.

I get a Promdapter1.cab has an invalid signature error.

**Comment by kallex** [comment]
That's odd. Do you use the latest release v 0.9.19, or what version?

The signature in the package is valid from 2020-08-28 to 2023-08-29 and its also timestamped, meaning that it shouldn't expire at all. I have installed it myself on 3 different Windows 10 machines with no issues.

I'm listing few things on top off my mind to check:

1. What's the clock + date of the system, could it be (way) off from real time, in the past?
2. Does the Properties-window of the file show the signatures or complain also?
2. I'm suspecting download corruption; can you try redownloading it?
3. Do you have overclocked system/RAM at any chance, is there a possibility it's not stable?

Have you had any previous versions without issues or is this your first download and installation attempt?

**Comment by kallex** [comment]
I will close this for now as no responses, reopen/comment more if needed.
